sudo: false
dist: trusty

language: rust

matrix:
  include:
  - rust: stable
  - rust: beta
  - rust: nightly
  - rust: stable
    os: windows
    env: ON_WINDOWS=1
  allow_failures:
  - os: windows

script:
  - ci/run.sh

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
