sudo: false
dist: trusty

language: rust

rust:
  - stable
  - beta
  - nightly

install:
  - rustc --version
  - ci/install-h2spec.sh
  - export PATH="$PATH:$(pwd)"

script:
  - ci/run.sh

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
